services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - user-service

  # document-service:
  #   build:
  #     context: ./backend/document-service
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3001:3001"
  #   environment:
  #     - NODE_ENV=development
  #     - DATABASE_URL=postgresql://user:password@db:5432/authentico_documents

  # verification-service:
  #   build:
  #     context: ./backend/verification-service
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3002:3002"
  #   environment:
  #     - NODE_ENV=development
  #     - DATABASE_URL=postgresql://user:password@db:5432/authentico_verifications

  user-service:
    build:
      context: ./backend/user-service
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://authentico_user:password@db:5432/authentico_users
    depends_on:
      - db
    volumes:
      - ./backend/user-service/prisma:/app/prisma
    networks:
      - default

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: authentico_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: authentico_users
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - default

  cypress:
    build:
      context: .
      dockerfile: Dockerfile.cypress
    depends_on:
      - frontend
    environment:
      - CYPRESS_baseUrl=http://frontend:3000
    networks:
      - default

volumes:
  postgres_data:

networks:
  default:













