// ...existing code...
function createUnhandledError(error: any) {
  // ...existing code...
  console.error('Unhandled error:', error.message || error, error.stack || '');
  // ...existing code...
}
// ...existing code...
